### PR TITLE
Talk a bit about interop and namespacing

### PR DESCRIPTION
**Pull request by divarvel**
https://twitter.com/schmichael/status/1534259856588255232

### CODE REVIEW

**Review by Geal — APPROVED** [review]

**Comment by apollo13** [comment]
This looks great, thank you! May I ask what "third party blocks" are?

**Comment by divarvel** [comment]
Third-party blocks are a development of the biscuit spec, not completely specified yet (even though there is a working implementation based on the haskell library): https://github.com/biscuit-auth/biscuit/pull/103

In a nutshell, while regular biscuits are based on the premise that only the authority block can be trusted (because it's signed by a well-known key), third party blocks are extra blocks that are also signed by well-known keys (that can be different from the authority key). Through a datalog syntax extension, it becomes possible to say "consider only facts coming from blocks have valid signatures for this specific public keys". That provides cryptographic segregation between facts.

**Comment by divarvel** [comment]
I have written down two example use cases for third-party blocks: https://github.com/biscuit-auth/website/issues/47 and https://github.com/biscuit-auth/website/issues/48

If you are familiar with macaroons, third-party blocks are an extension of third-party caveats: they make it possible to have a macaroons that's only valid if a third party validates a specific claim it carries. Third party blocks extend that by not only enabling third party checks, but also letting third parties embed facts as well.

**Comment by apollo13** [comment]
Thanks, that looks interesting (and a lot to process :)).

**Pull request merged**
